(copy_files
 (alias target_platform)
 (only_sources)
 (enabled_if
  (= %{env:TARGET_PLATFORM=ppc} ppc))
 (files %{project_root}/powerpc/*))

(copy_files
 (alias target_platform)
 (only_sources)
 (enabled_if
  (= %{env:TARGET_PLATFORM=ppc} x86_64))
 (files %{project_root}/x86/*.{v,vp,ml,mli}))

(copy_files
 (alias target_platform)
 (only_sources)
 (enabled_if
  (= %{env:TARGET_PLATFORM=ppc} x86_64))
 (files %{project_root}/x86_64/*.{v,vp,ml,mli}))

(copy_files
 (alias target_platform)
 (only_sources)
 (enabled_if
  (= %{env:TARGET_PLATFORM=ppc} riscV))
 (files %{project_root}/riscV/*))

(copy_files
 (alias target_platform)
 (only_sources)
 (enabled_if
  (= %{env:TARGET_PLATFORM=ppc} arm))
 (files %{project_root}/arm/*))

(copy_files
 (alias target_platform)
 (only_sources)
 (enabled_if
  (= %{env:TARGET_PLATFORM=ppc} aarch64))
 (files %{project_root}/aarch64/*))

(subdir
 backend
 (copy_files %{project_root}/backend/*))

(subdir
 cfrontend
 (copy_files %{project_root}/cfrontend/*))

(subdir
 common
 (copy_files %{project_root}/common/*))

(subdir
 cparser
 (copy_files %{project_root}/cparser/*))

(subdir
 debug
 (copy_files %{project_root}/debug/*))

(subdir
 driver
 (copy_files %{project_root}/driver/*))

(subdir
 export
 (copy_files %{project_root}/export/*))

(subdir
 lib
 (copy_files %{project_root}/lib/*))

(include preprocess.dune)

(rocq.theory
 (name compcert)
 (theories Flocq MenhirLib)
 (flags
  -w
  -unused-pattern-matching-variable
  -w
  -deprecated-since-8.19
  -w
  -deprecated-since-8.20)
 (modules
  :standard
  \
  common.Subtyping
  extractionMachdep
  extractionMachdepClight))

(include_subdirs qualified)
